const dictionary = [
    { id: 'w1', type: 'word', word: "Һаумыһығыҙ", trans: "Здравствуйте", phonetic: "Hau-my-hy-gyz", tts: "Хаумыхыгыз" },
    { id: 'w2', type: 'word', word: "Сәләм", trans: "Привет", phonetic: "Sa-lam", tts: "Сэлям" },
    { id: 'w3', type: 'word', word: "Хәлдәр нисек?", trans: "Как дела?", phonetic: "Hal-dar ni-sek", tts: "Хэлдэр нисек" },
    { id: 'w4', type: 'word', word: "Рәхмәт", trans: "Спасибо", phonetic: "Rakh-mat", tts: "Рэхмэт" },
    { id: 'w5', type: 'word', word: "Зинһар", trans: "Пожалуйста", phonetic: "Zin-har", tts: "Зинхар" },
    { id: 'w6', type: 'word', word: "Именлек", trans: "Благополучие", phonetic: "I-men-lek", tts: "Именлек" },
    { id: 'w7', type: 'word', word: "Дуҫлыҡ", trans: "Дружба", phonetic: "Dus-lyk", tts: "Дуслык" },
    { id: 'w8', type: 'word', word: "Яратам", trans: "Люблю", phonetic: "Ya-ra-tam", tts: "Яратам" },
    { id: 'w9', type: 'word', word: "Тыуған ил", trans: "Родина", phonetic: "Tiu-gan il", tts: "Тыуган ил" },
    { id: 'w10', type: 'word', word: "Матур", trans: "Красивый", phonetic: "Ma-tur", tts: "Матур" },
    { id: 'w11', type: 'word', word: "Башҡортостан", trans: "Башкирия", phonetic: "Bash-qor-tos-tan", tts: "Башкортостан" },
    { id: 'w12', type: 'word', word: "Өфө", trans: "Уфа", phonetic: "O-fo", tts: "Офо" },
    { id: 'w13', type: 'word', word: "Бал", trans: "Мёд", phonetic: "Bal", tts: "Бал" },
    { id: 'w14', type: 'word', word: "Ҡурай", trans: "Курай", phonetic: "Qu-ray", tts: "Курай" },
    { id: 'w15', type: 'word', word: "Аш", trans: "Суп / Еда", phonetic: "Ash", tts: "Аш" }
];

const alphabet = [
    { id: 'l1', letter: "А а", sound: "Как русское 'а'", tts: "А" },
    { id: 'l2', letter: "Б б", sound: "Как русское 'б'", tts: "Б" },
    { id: 'l3', letter: "В в", sound: "Как русское 'в'", tts: "В" },
    { id: 'l4', letter: "Г г", sound: "Как русское 'г'", tts: "Г" },
    { id: 'l5', letter: "Ғ ғ", sound: "Горловое 'г'", tts: "Ғ" },
    { id: 'l6', letter: "Д д", sound: "Как русское 'д'", tts: "Д" },
    { id: 'l7', letter: "Ҙ ҙ", sound: "Межзубное 'з' (как th в the)", tts: "Ҙ" },
    { id: 'l8', letter: "Е е", sound: "Как русское 'е'", tts: "Е" },
    { id: 'l9', letter: "Ё ё", sound: "Как русское 'ё'", tts: "Ё" },
    { id: 'l10', letter: "Ж ж", sound: "Как русское 'ж'", tts: "Ж" },
    { id: 'l11', letter: "З з", sound: "Как русское 'з'", tts: "З" },
    { id: 'l12', letter: "И и", sound: "Как русское 'и'", tts: "И" },
    { id: 'l13', letter: "Й й", sound: "Как русское 'й'", tts: "Й" },
    { id: 'l14', letter: "К к", sound: "Как русское 'к'", tts: "К" },
    { id: 'l15', letter: "Ҡ ҡ", sound: "Глубокое 'к'", tts: "Ҡ" },
    { id: 'l16', letter: "Л л", sound: "Как русское 'л'", tts: "Л" },
    { id: 'l17', letter: "М м", sound: "Как русское 'м'", tts: "М" },
    { id: 'l18', letter: "Н н", sound: "Как русское 'н'", tts: "Н" },
    { id: 'l19', letter: "Ң ң", sound: "Носовое 'н'", tts: "Ң" },
    { id: 'l20', letter: "О о", sound: "Как русское 'о'", tts: "О" },
    { id: 'l21', letter: "Ө ө", sound: "Мягкое 'о', как в 'мёд'", tts: "Ө" },
    { id: 'l22', letter: "П п", sound: "Как русское 'п'", tts: "П" },
    { id: 'l23', letter: "Р р", sound: "Как русское 'р'", tts: "Р" },
    { id: 'l24', letter: "С с", sound: "Как русское 'с'", tts: "С" },
    { id: 'l25', letter: "Ҫ ҫ", sound: "Межзубное 'с' (как th в think)", tts: "Ҫ" },
    { id: 'l26', letter: "Т т", sound: "Как русское 'т'", tts: "Т" },
    { id: 'l27', letter: "У у", sound: "Как русское 'у'", tts: "У" },
    { id: 'l28', letter: "Ү ү", sound: "Мягкое 'у', губы трубочкой", tts: "Ү" },
    { id: 'l29', letter: "Ф ф", sound: "Как русское 'ф'", tts: "Ф" },
    { id: 'l30', letter: "Х х", sound: "Как русское 'х'", tts: "Х" },
    { id: 'l31', letter: "Һ һ", sound: "Мягкое придыхание 'х'", tts: "Һ" },
    { id: 'l32', letter: "Ц ц", sound: "Как русское 'ц'", tts: "Ц" },
    { id: 'l33', letter: "Ч ч", sound: "Как русское 'ч'", tts: "Ч" },
    { id: 'l34', letter: "Ш ш", sound: "Как русское 'ш'", tts: "Ш" },
    { id: 'l35', letter: "Щ щ", sound: "Как русское 'щ'", tts: "Щ" },
    { id: 'l36', letter: "Ъ ъ", sound: "Твердый знак", tts: "" },
    { id: 'l37', letter: "Ы ы", sound: "Как русское 'ы'", tts: "Ы" },
    { id: 'l38', letter: "Ь ь", sound: "Мягкий знак", tts: "" },
    { id: 'l39', letter: "Э э", sound: "Как русское 'э'", tts: "Э" },
    { id: 'l40', letter: "Ю ю", sound: "Как русское 'ю'", tts: "Ю" },
    { id: 'l41', letter: "Я я", sound: "Как русское 'я'", tts: "Я" }
];
